name: Component Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Run Component tests
        uses: cypress-io/github-action@v2
        with:
          install: true
          command: yarn cy:run-ct
          install-command: yarn --frozen-lockfile
      - name: Install and Build Storybook
        run: |
          yarn --frozen-lockfile
          yarn build-storybook
      - name: Deploy Storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: storybook-static
          ssh-key: ${{ secrets.DEPLOY_KEY }}
